[package]
name = "HW_VT_PROJET"
version = "0.1.0"
edition = "2021"

[dependencies]
avr-device = { version = "0.4.0", features = ["atmega328p"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[target.'cfg(target_arch = "avr")']
rustflags = ["-C", "target-cpu=atmega328p"]
